version: '3.5'

services:
    painter_bot:
        image: painter_bot_img:latest
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: painter_bot
#       restart: always
        env_file: .env
        networks:
            - painter_net
        volumes:
            - ./source:/root/project
            - ./checkpoint:/var/tmp/checkpoint

networks:
    painter_net:
